#!/usr/bin/env bash
# setup.sh — verify env, compile tracker, smoke-test, generate shell aliases.
# Idempotent: re-running regenerates aliases.sh with the current path.

set -euo pipefail

cd "$(dirname "$0")"
ROOT="$(pwd)"

echo "→ checking Go..."
if ! command -v go >/dev/null 2>&1; then
  echo "✗ go not on PATH. install from https://go.dev/dl/ and re-run." >&2
  exit 1
fi

GO_VERSION="$(go env GOVERSION | sed 's/^go//')"      # e.g. 1.26.2
GO_MAJOR="$(echo "$GO_VERSION" | cut -d. -f1)"
GO_MINOR="$(echo "$GO_VERSION" | cut -d. -f2)"
if [ "$GO_MAJOR" -lt 1 ] || { [ "$GO_MAJOR" -eq 1 ] && [ "$GO_MINOR" -lt 26 ]; }; then
  echo "✗ need Go ≥ 1.26, found $GO_VERSION. upgrade via https://go.dev/dl/" >&2
  exit 1
fi
echo "  go $GO_VERSION ok"

echo "→ building tracker binary..."
go build -o ./tracker ./cmd/tracker
echo "  ./tracker ok"

echo "→ smoke-testing internal packages..."
go test ./internal/... >/dev/null
echo "  ok"

echo "→ writing aliases.sh..."
if [ -f aliases.sh ]; then
  echo "  aliases.sh exists, leaving it alone (delete it to regenerate)"
else
  cat > aliases.sh <<EOF
# learning-plan shell aliases — generated by setup.sh on first run.
# Feel free to edit this file; setup.sh will not overwrite it. Delete it to regenerate.
#
# Activate in current shell:
#     source "$ROOT/aliases.sh"
# Make permanent (zsh):
#     echo 'source "$ROOT/aliases.sh"' >> ~/.zshrc
# Make permanent (bash):
#     echo 'source "$ROOT/aliases.sh"' >> ~/.bashrc
#
# Note: 'lp' shadows the macOS/Linux printer command. If you need the printer,
# use 'command lp' or '\lp'. Or rename the function below to 'lpt' / 'study' / etc.

lp() {
  "$ROOT/tracker" "\$@"
}
EOF
  echo "  wrote aliases.sh"
fi

cat <<EOF

✓ setup complete.

shell aliases (one 'lp' alias for the whole tracker):
  one-time in current shell:
    source "$ROOT/aliases.sh"

  permanent (zsh):
    echo 'source "$ROOT/aliases.sh"' >> ~/.zshrc

next steps (after sourcing aliases.sh):
  lp serve                               # dashboard on http://localhost:8080
  lp place phase-0                       # diagnostic quiz — skip what you know
  lp verify 1.1-hello-world              # run the first exercise

without aliases, use the long form:
  go run ./cmd/tracker serve
  go run ./cmd/tracker place phase-0
  go run ./cmd/tracker verify 1.1-hello-world

read the learner-facing docs:
  README.md             what this is, quick start
  curriculum-v2.md      the 43-task curriculum
  claude.md             how to pair-mentor with Claude Code
  explorations/         skill trees for third-party repos
EOF
