#!/usr/bin/env bash
# setup.sh — verify env, compile go-dojo, smoke-test, generate shell function.
# Idempotent: re-running regenerates aliases.sh with the current path.

set -euo pipefail

cd "$(dirname "$0")"
ROOT="$(pwd)"

echo "→ checking Go..."
if ! command -v go >/dev/null 2>&1; then
  echo "✗ go not on PATH. install from https://go.dev/dl/ and re-run." >&2
  exit 1
fi

GO_VERSION="$(go env GOVERSION | sed 's/^go//')"      # e.g. 1.26.2
GO_MAJOR="$(echo "$GO_VERSION" | cut -d. -f1)"
GO_MINOR="$(echo "$GO_VERSION" | cut -d. -f2)"
if [ "$GO_MAJOR" -lt 1 ] || { [ "$GO_MAJOR" -eq 1 ] && [ "$GO_MINOR" -lt 26 ]; }; then
  echo "✗ need Go ≥ 1.26, found $GO_VERSION. upgrade via https://go.dev/dl/" >&2
  exit 1
fi
echo "  go $GO_VERSION ok"

echo "→ building go-dojo binary..."
VERSION="$(cat VERSION 2>/dev/null || echo dev)"
COMMIT="$(git rev-parse --short HEAD 2>/dev/null || echo none)"
BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
LDFLAGS="-X main.Version=${VERSION} -X main.Commit=${COMMIT} -X main.BuildDate=${BUILD_DATE}"
go build -ldflags "${LDFLAGS}" -o ./go-dojo ./cmd/go-dojo
echo "  ./go-dojo ${VERSION} (${COMMIT})"

echo "→ smoke-testing internal packages..."
go test ./internal/... >/dev/null
echo "  ok"

echo "→ writing aliases.sh..."
if [ -f aliases.sh ]; then
  echo "  aliases.sh exists, leaving it alone (delete it to regenerate)"
else
  cat > aliases.sh <<EOF
# go-dojo shell function — generated by setup.sh on first run.
# Feel free to edit this file; setup.sh will not overwrite it. Delete it to regenerate.
#
# Activate in current shell:
#     source "$ROOT/aliases.sh"
# Make permanent (zsh):
#     echo 'source "$ROOT/aliases.sh"' >> ~/.zshrc
# Make permanent (bash):
#     echo 'source "$ROOT/aliases.sh"' >> ~/.bashrc
#
# Function name uses a hyphen (\`go-dojo\`). This is valid in zsh and bash;
# rename to 'golearn' or 'study' below if your shell doesn't accept hyphens.

go-dojo() {
  "$ROOT/go-dojo" "\$@"
}
EOF
  echo "  wrote aliases.sh"
fi

cat <<EOF

✓ setup complete.

shell function 'go-dojo' (source aliases.sh to activate):
  one-time in current shell:
    source "$ROOT/aliases.sh"

  permanent (zsh):
    echo 'source "$ROOT/aliases.sh"' >> ~/.zshrc

next steps (after sourcing aliases.sh):
  go-dojo serve                         # dashboard on http://localhost:8080
  go-dojo placement phase-0             # diagnostic quiz — skip what you know
  go-dojo verify 1.1-hello-world        # run the first exercise

without the function sourced, use the long form:
  go run ./cmd/go-dojo serve
  go run ./cmd/go-dojo placement phase-0
  go run ./cmd/go-dojo verify 1.1-hello-world

read the learner-facing docs:
  README.md             what this is, quick start
  curriculum-v2.md      the 43-task curriculum
  claude.md             how to pair-mentor with Claude Code
  explorations/         skill trees for third-party repos
EOF
